"use client";

import { ReflectionReport } from "@/lib/api/report";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Download, Calendar, Sparkles } from "lucide-react";
import { useRef } from "react";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

interface ReportViewerProps {
    report: ReflectionReport;
}

export function ReportViewer({ report }: ReportViewerProps) {
    const printRef = useRef<HTMLDivElement>(null);

    const handleDownload = async () => {
        if (!printRef.current) return;

        const canvas = await html2canvas(printRef.current, { scale: 2 });
        const imgData = canvas.toDataURL("image/png");
        const pdf = new jsPDF("p", "mm", "a4");
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

        pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
        pdf.save(`MindEase-Reflection-${new Date(report.createdAt).toISOString().slice(0, 10)}.pdf`);
    };

    return (
        <div className="space-y-6">
            <div className="flex justify-end">
                <Button onClick={handleDownload} variant="outline" className="gap-2">
                    <Download className="h-4 w-4" />
                    Download PDF
                </Button>
            </div>

            <div ref={printRef} className="bg-white p-8 rounded-lg shadow-sm border space-y-8 text-slate-800">
                {/* Header */}
                <div className="border-b pb-6 text-center space-y-2">
                    <h1 className="text-3xl font-serif text-slate-900 tracking-tight">Wellbeing Reflection</h1>
                    <p className="text-slate-500 font-medium">
                        {new Date(report.startDate).toLocaleDateString()} — {new Date(report.endDate).toLocaleDateString()}
                    </p>
                    <div className="flex items-center justify-center gap-2 text-primary pt-2">
                        <Sparkles className="h-4 w-4" />
                        <span className="text-sm font-medium">AI-Generated Reflection</span>
                    </div>
                </div>

                {/* content */}
                <div className="grid gap-8">
                    {/* Mood & Activity Summary */}
                    <div className="grid md:grid-cols-2 gap-8">
                        <div className="space-y-3">
                            <h3 className="text-lg font-semibold text-slate-800 border-b pb-2">Mood Patterns</h3>
                            <p className="leading-relaxed text-slate-600">{report.content.moodSummary}</p>
                        </div>
                        <div className="space-y-3">
                            <h3 className="text-lg font-semibold text-slate-800 border-b pb-2">Activity Engagement</h3>
                            <p className="leading-relaxed text-slate-600">{report.content.activitySummary}</p>
                        </div>
                    </div>

                    {/* Main Reflection */}
                    <div className="bg-slate-50 p-6 rounded-xl border border-slate-100 space-y-4">
                        <h3 className="text-lg font-semibold text-slate-800">A Moment of Reflection</h3>
                        <p className="leading-7 text-slate-700 whitespace-pre-wrap">{report.content.reflection}</p>
                    </div>

                    {/* Suggestions */}
                    <div className="space-y-4">
                        <h3 className="text-lg font-semibold text-slate-800 border-b pb-2">Gentle Suggestions</h3>
                        <p className="leading-relaxed text-slate-600">{report.content.suggestions}</p>
                    </div>
                </div>

                {/* Footer */}
                <div className="pt-8 mt-8 border-t text-center text-xs text-slate-400">
                    <p>Generated by MindEase. This is a reflection, not a medical evaluation.</p>
                </div>
            </div>
        </div>
    );
}
